### ISSUE TITLE
tcp程序运行一段时间就会出现 `Rout fail` 的问题，导致所有接口无法请求

### ISSUE THREAD

**Issue by dmf-code** [TarsPHP/tars-client#11]
这是在 `tars-client` 打印的信息，之前一直这个错误，然后打印信息发现没获取到 `_routeInfo` 的信息。
![image](https://user-images.githubusercontent.com/22268578/86696541-1e7a6880-c040-11ea-9ea5-3ea1c94fd757.png)

![image](https://user-images.githubusercontent.com/22268578/86696564-233f1c80-c040-11ea-9b3d-f91b5b8041e1.png)

`tars web` 显示的版本信息 `Version:2.4.0`
`docker` 版本
```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:27:04 2020
 OS/Arch:           linux/amd64
 Experimental:      false
```

**Comment by dmf-code** [comment]
使用的是 `SocketMode`: 1 这种模式，然后会出现双方tcp建立连接，之后一直阻塞。

**Comment by dmf-code** [comment]
暂时解决方案是使用 `SocketMode`: 2 模式，使用 `swoole` 客户端能够很好处理 `socket` 超时问题，但是问题是如何发生的还是不清楚。

**Comment by meijing0114** [comment]
此问题需要定位

**Comment by dmf-code** [comment]
> 此问题需要定位

不好意思，这个问题是我这边造成的。这个 `socket` 无法关闭是因为我在自身项目中调用 `TCP` 服务了，导致出现 `socket` 一直等待数据接收。
![image](https://user-images.githubusercontent.com/22268578/87931709-cb32fc00-cabc-11ea-849d-f61b17852445.png)
