### ISSUE TITLE
tests 里的 composer 配置有问题

### ISSUE THREAD

**Issue by fuhehe** [TarsPHP/tars-client#3]
在tests里运行 composer install 会出现：
[Composer\Downloader\TransportException]                                                                                                 
  The "https://raw.githubusercontent.com/Tencent/Tars/master/php/dist/tarsphp.json" file could not be downloaded (HTTP/1.1 404 Not Found)
删除 composer.json 里的 repositories 字段后，会出现：
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - The requested package phptars/tars-client 0.1.1 exists as phptars/tars-client[0.1.5, dev-master] but these are rejected by your constraint.
而后只有将 require 中的 phptars/tars-client 的版本由 0.1.1 改为 ~0.1.1 才可以

**Comment by i838847058** [comment]
- 1

**Comment by zhangdang254** [comment]
👍

**Comment by xiaoluozi513** [comment]
problem:
1.The "https://raw.githubusercontent.com/Tencent/Tars/master/php/dist/tarsphp.json" file could not be downloaded (HTTP/1.1 404 Not Found)
2.PHP Fatal error:  Uncaught Error: Class 'PHPTest\PHPServer\obj\TestTafServiceServant' not found

**Comment by meijing0114** [comment]
Fixed
