### ISSUE TITLE
Tars\client\ResponsePacket->decode()

### ISSUE THREAD

**Issue by liyunde** [TarsPHP/tars-client#5]
phptars/tars-client 0.3.0
TestApp.HelloServer
c++和 java 都可以通,只是 PHP 会直接出异常
vendor/phptars/tars-client/src/ResponsePacket.php:22
vendor/phptars/tars-client/src/Communicator.php(145): Tars\client\ResponsePacket->decode()

是不是需要其他配置

debug 看到解码失败
\TUPAPI::decode($this->_responseBuf, $this->iVersion);
iRet = {int} -4
sResultDesc = ""

**Comment by imzeali** [comment]
@liyunde 你好，请问你解决了吗，我用 指定服务 也遇到这个问题

**Comment by dpp2009** [comment]
iRet不为0  是底层报错

const int TARSSERVERSUCCESS       = 0;       //服务器端处理成功
const int TARSSERVERDECODEERR     = -1;      //服务器端解码异常
const int TARSSERVERENCODEERR     = -2;      //服务器端编码异常
const int TARSSERVERNOFUNCERR     = -3;      //服务器端没有该函数
const int TARSSERVERNOSERVANTERR  = -4;      //服务器端没有该Servant对象
const int TARSSERVERRESETGRID     = -5;      //服务器端灰度状态不一致
const int TARSSERVERQUEUETIMEOUT  = -6;      //服务器队列超过限制
const int TARSASYNCCALLTIMEOUT    = -7;      //异步调用超时
const int TARSINVOKETIMEOUT       = -7;      //调用超时
const int TARSPROXYCONNECTERR     = -8;      //proxy链接异常
const int TARSSERVEROVERLOAD      = -9;      //服务器端超负载,超过队列长度
const int TARSADAPTERNULL         = -10;     //客户端选路为空，服务不存在或者所有服务down掉了
const int TARSINVOKEBYINVALIDESET = -11;     //客户端按set规则调用非法
const int TARSCLIENTDECODEERR     = -12;     //客户端解码异常
const int TARSSERVERUNKNOWNERR    = -99;     //服务器端位置异常
